### ISSUE TITLE
[BUG] UI not working, not even the script is generated

### ISSUE THREAD

**Issue by ipharksai** [leamsigc/ShortsGenerator#3]
I installed the whole thing, put in all the variables and everything. But how to start it is a little confusing to me., here is what I do:
In terminal window 1:
'docker-compose up -d'

In terminal window 2:
cd UI
'npm run dev'

Then I open a new tab and enter
'http://localhost:5000'

There I see the UI (I guess?). However it is like it did not finish loading or something?

![image](https://github.com/leamsigc/ShortsGenerator/assets/166437335/e18ddec9-02e5-41c3-add9-e2ebd3da934e)

The sections "Select audio" and "SubTitle Settings" have no input window.

When I click the rectangle symbol for fullscreen I get to see the 4 other "pages" (settings, generate, videos, documentation).
When I go to, e.g., generate, I can write something and click generate, and then nothing happens.

Thing is I cannot see any error message anywhere whatsoever. Since I am not very versed in programming I do not konw where to start to find the problem.

To reproduce: I can do it again, same behavior.

Also, I tried a similar approach following what it shows under "documentation" (
![image](https://github.com/leamsigc/ShortsGenerator/assets/166437335/d6468b64-b084-476a-bf39-0e9ac27732e7)

settings
Generate
Videos
Documentation
Search...CTRL K
Full Screen
Documentation related to the Money Printer UI
[Project roadmap](http://localhost:5000/docs/road-map)
Getting started
We have two options to get started
Option one: Local installation
Install requirements
pip install -r requirements.txt
Copy .env.example and fill out values
cp .env.example .env
Run the backend server
cd Backend
python main.py
Run the frontend server
cd ../Frontend
python -m http.server 3000
Run the nuxt front end
cd ../UI
npm install
npm run dev

Option one: Docker container
1.	Build the docker image
docker-compose build --no-cache
2.	Run the docker container
docker-compose up -d
3.	The fallowing port urls will be available
[Backend](http://localhost:8080/)
[Frontend](http://localhost:3000/) -> Basic frontend -> The port will be 3000 by default in the env but you can change it in the .env
[Frontend](http://localhost:5000/) -> Nuxt frontend -> The port will be 5000 by default in the env but you can change it in the .env
Money Printer UI
)

Here I run into the same problem though.

Any idea what I can do?

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser 
 - Python Version 3.10.10

**Comment by leamsigc** [comment]
Is the back end service in the right port ? 8080 
- Can you pull and try it again 


Another question is related to are you using the local development right or the container ?




Is there any error on the console?



- The other option is to go to the general settings select the ai model then got to generate and try
-

**Comment by UltraInstinct0x** [comment]
@ipharksai as you only shared what you have done instead of logs from the docker (I just use docker whenever its available), I cannot help much. 
But the problem I have faced was with the imagemagick binary. You have to set it correctly according to your environment. As you are on a windows machine, you must have imagemagick "installed" in your computer, most probably on C drive, under program files, under ImageMagick folder. 
After that you can use the path on .env file like 
`IMAGEMAGICK_BINARY="C:\\Program Files\\ImageMagick-7.1.0-Q16\\magick.exe`

Use your own version and path of course.

# And for all the others here are the Mac references:

- For Apple Silicone (if you used homebrew to install it)
`/opt/homebrew/Cellar/imagemagick/7.1.1-27/bin/magick`

- For Intel Macs
`/usr/local/Cellar/imagemagick/`

I will try to contribute to readme file tomorrow.

**Comment by leamsigc** [comment]
I update the docker container now so not docker compose up and should be done
